# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761461f6b3ab1788cc7d9832605c4147ff51cdb619ac3ce0e8263f93912f73b011f9693b3bc24f2d1bebe9fe4dbcb5d4c2fdaf8111d5b24e5e7c218f9cf92a63

test:
  secret_key_base: 55d9f627f3f45035a9b93108ba3a9cfc319b2e72a46bc9b491c9cfe534415a87df144a65e2e475ac53d0f361a95ea039d99a3970f7b9d0ae521c5b48e3cc2d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
